
import java.sql.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author davidesfandiary
 */
public class editSuppliers extends javax.swing.JFrame {

    /**
     * Creates new form editSuppliers
     */
    
    private loggedIn parentPage;
    
    public editSuppliers() {
        initComponents();
        loadCB();
    }
    
    public editSuppliers(loggedIn parentPage) {
        initComponents();
        //loadCB();
        suppliersCB.setVisible(false);
        this.parentPage = parentPage;
        
        
        fillData();
        
        
    }
    
    private void fillData(){
        JTable table = parentPage.getSuppliersTable();
        int row = table.getSelectedRow();

        this.rowName = table.getValueAt(row, 0).toString();
        this.rowContact = table.getValueAt(row, 1).toString();

        suppliersNameTF.setText(this.rowName);
        suppliersContactTF.setText(this.rowContact);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        suppliersCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        suppliersNameTF = new javax.swing.JTextField();
        suppliersContactTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        suppliersDeleteBTN = new javax.swing.JButton();
        suppliersUpdateBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        suppliersCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersCBActionPerformed(evt);
            }
        });

        jLabel2.setText("Edit Suppliers Table");

        jLabel3.setText("Supplier Name:");

        suppliersNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersNameTFActionPerformed(evt);
            }
        });

        jLabel4.setText("Contact Info:");

        suppliersDeleteBTN.setText("Delete");
        suppliersDeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersDeleteBTNActionPerformed(evt);
            }
        });

        suppliersUpdateBTN.setText("Update");
        suppliersUpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersUpdateBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(suppliersDeleteBTN)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(suppliersContactTF, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(suppliersNameTF)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(suppliersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(suppliersUpdateBTN)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(suppliersCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(suppliersNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(suppliersContactTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suppliersDeleteBTN)
                    .addComponent(suppliersUpdateBTN))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static final String dburl = "jdbc:mysql://localhost:3306/finals";
    private static final String dbusername = "root";
    private static final String dbpassword = "rootroot";
    private String rowName = "";
    private String rowContact = "";

    public final void loadCB() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(dburl, dbusername, dbpassword);

            Statement statement;
            statement = con.createStatement();
            ResultSet sqlresult;
            sqlresult = statement.executeQuery("select * from suppliers");
            
            suppliersCB.removeAllItems();

            while(sqlresult.next()) {
                suppliersCB.addItem(sqlresult.getString("supplier_id") + " - " + sqlresult.getString("supplier_name"));
            }
            
        }    
            catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    
    }
    
    private void suppliersNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliersNameTFActionPerformed

    private void suppliersDeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersDeleteBTNActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(dburl, dbusername, dbpassword);
            Statement statement = con.createStatement();
            
            
      
            String query = "DELETE FROM Suppliers WHERE supplier_name = ? AND contact_info = ?";
           
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, this.rowName);
            preparedStatement.setString(2, this.rowContact);

            preparedStatement.executeUpdate();
            
            suppliersNameTF.setText("");
            suppliersContactTF.setText("");
            
            parentPage.loadTable();
            loadCB();
            parentPage.loadSuppliersCB(parentPage.getPOrdersSuppliersCB());
            this.setVisible(false);
            
            statement.close();
            con.close();
            
        } catch(Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_suppliersDeleteBTNActionPerformed

    private void suppliersUpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersUpdateBTNActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(dburl, dbusername, dbpassword);
            Statement statement = con.createStatement();
            String name = suppliersNameTF.getText();
            String contact = suppliersContactTF.getText();
            
      
            String query = "UPDATE Suppliers SET supplier_name = ?, contact_info = ? WHERE supplier_name = ? AND contact_info = ?";
           
            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, name);
            preparedStatement.setString(2, contact);
            preparedStatement.setString(3, this.rowName);
            preparedStatement.setString(4, this.rowContact);
            preparedStatement.executeUpdate();
           
            
            parentPage.loadTable();
            parentPage.loadSuppliersCB(parentPage.getPOrdersSuppliersCB());
            this.setVisible(false);
            
            statement.close();
            con.close();
            
        } catch(Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_suppliersUpdateBTNActionPerformed

    private void suppliersCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersCBActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(dburl, dbusername, dbpassword);

            //Statement statement = con.createStatement();

            String selected = suppliersCB.getSelectedItem().toString();

            String[] id = selected.split(" - ");

            String query = "SELECT * FROM Suppliers WHERE supplier_id = ?";

            PreparedStatement preparedStatement = con.prepareStatement(query);
            preparedStatement.setString(1, id[0]);

            ResultSet sqlresult = preparedStatement.executeQuery();

            while(sqlresult.next()) {
                suppliersNameTF.setText(sqlresult.getString("supplier_name"));
                suppliersContactTF.setText(sqlresult.getString("contact_info"));
            }

        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_suppliersCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editSuppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> suppliersCB;
    private javax.swing.JTextField suppliersContactTF;
    private javax.swing.JButton suppliersDeleteBTN;
    private javax.swing.JTextField suppliersNameTF;
    private javax.swing.JButton suppliersUpdateBTN;
    // End of variables declaration//GEN-END:variables
}
